services:
  pipeline:
    image: aapashkov/pancluster
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
      - HOME=/home/user
    working_dir: /ext
    volumes:
      - ./:/ext
    command: make -j${JOBS}
